### ISSUE TITLE
Update uix dependency

### ISSUE THREAD

**Issue by yissachar** [cgarciae/uix_shortcuts#3]
Version 0.6.0 is available.

Thanks for this library by the way - it's very useful for making uix code more readable.

**Comment by cgarciae** [comment]
Hi,

I just increased the dependencies in a new version to `uix: ">=0.5.0 <1.0.0"` assuming `0.6.0` is compatible with the shortcuts. If its not, let me know.

**Comment by yissachar** [comment]
Works great, thanks :+1:
